/**
 * NaviCampus UAE - High-Precision Spatial Database
 * Reverse-Engineered from Official Campus Blueprints:
 * - University of Sharjah (UoS) 2026 Campus Masterplan (uos_map.pdf)
 * - American University of Sharjah (AUS) Masterplan (aus_map.pdf)
 * - RIT Dubai Silicon Oasis Innovation Campus
 * 
 * Complies with Swiss Graphic Design Standards for spatial visualization.
 */

const CAMPUS_DATA = {
  uos: {
    id: "uos",
    name: "University of Sharjah",
    shortName: "UoS",
    fullName: "University of Sharjah — Main & Medical Campus",
    city: "Sharjah University City, UAE",
    viewBox: "0 0 1000 1600",
    defaultCenter: { x: 500, y: 550 },
    defaultZoom: 1,
    description: "Multi-acre linear campus organized into Zone A (Men's), Zone B (Central Admin), Zone C (Women's), and Zone E (Medical & Health Sciences).",
    sectors: [
      { id: "all", name: "Full Campus", bounds: { minX: 0, minY: 0, maxX: 1000, maxY: 1600 } },
      { id: "zone_a", name: "Zone A (Men's & Eng.)", bounds: { minX: 100, minY: 50, maxX: 900, maxY: 650 } },
      { id: "zone_b", name: "Zone B (Administration)", bounds: { minX: 150, minY: 600, maxX: 850, maxY: 800 } },
      { id: "zone_c", name: "Zone C (Women's)", bounds: { minX: 100, minY: 750, maxX: 900, maxY: 1200 } },
      { id: "zone_e", name: "Zone E (Medical & Hospital)", bounds: { minX: 100, minY: 1180, maxX: 900, maxY: 1580 } }
    ],
    quickJumps: [
      { label: "Engineering M8/M9 (A13)", targetId: "uos-a13", room: "M8-102", icon: "engineering" },
      { label: "Computing & IT (A9)", targetId: "uos-a9", room: "CCI-204", icon: "computing" },
      { label: "Central Library (A7)", targetId: "uos-a7", room: "2nd Floor Silent Zone", icon: "library" },
      { label: "Student Center & Dining (A4/A5)", targetId: "uos-a5", room: "Food Court", icon: "dining" },
      { label: "Registrar Office (B2)", targetId: "uos-b2", room: "Admissions Counter", icon: "admin" },
      { label: "Women's Engineering W9 (C13)", targetId: "uos-c13", room: "W9-015", icon: "engineering" },
      { label: "College of Medicine (E5)", targetId: "uos-e5", room: "Main Amphitheater", icon: "medical" }
    ],
    buildings: [
      // === ZONE A: MEN'S CAMPUS ===
      {
        id: "uos-a19",
        code: "A19",
        name: "UoS Stadium & Athletics",
        nameAr: "استاد جامعة الشارقة",
        zone: "Zone A",
        category: "sports",
        x: 180, y: 70, width: 140, height: 75,
        rooms: ["Field", "Grandstand", "Locker Rooms"],
        facilities: ["Football Pitch", "Running Track", "Athletic Training Room"],
        entranceNode: "n_a19",
        accessible: true
      },
      {
        id: "uos-a1",
        code: "A1",
        name: "Ibn Rushd Building",
        nameAr: "مبنى ابن رشد",
        zone: "Zone A",
        category: "academic",
        departments: ["College of Sharia & Islamic Studies", "Research Institute of Science & Eng (RISE)"],
        x: 430, y: 120, width: 110, height: 80,
        rooms: ["A1-101", "A1-104", "RISE Lab 2", "Seminar Hall"],
        facilities: ["RISE Labs", "Faculty Offices", "Prayer Room (Ground Floor)", "Conference Hall"],
        entranceNode: "n_a1",
        accessible: true
      },
      {
        id: "uos-a2",
        code: "A2",
        name: "Ibn Khaldun Building",
        nameAr: "مبنى ابن خلدون",
        zone: "Zone A",
        category: "academic",
        departments: ["College of Arts, Humanities & Social Sciences", "College of Law"],
        x: 370, y: 225, width: 130, height: 60,
        rooms: ["A2-105", "A2-110", "Moot Court", "Language Lab"],
        facilities: ["Moot Court", "Law Library Annex", "Elevator West", "Ramp Access"],
        entranceNode: "n_a2",
        accessible: true
      },
      {
        id: "uos-a3",
        code: "A3",
        name: "Ibn Al-Haytham Building",
        nameAr: "مبنى ابن الهيثم",
        zone: "Zone A",
        category: "academic",
        departments: ["College of Graduate Studies"],
        x: 420, y: 300, width: 100, height: 60,
        rooms: ["A3-201", "A3-205", "Thesis Defense Room"],
        facilities: ["Graduate Studies Dean", "Research Desks", "Quiet Lounge"],
        entranceNode: "n_a3",
        accessible: true
      },
      {
        id: "uos-a4",
        code: "A4",
        name: "Men's Dining Hall",
        nameAr: "مجمع المطاعم - طالب",
        zone: "Zone A",
        category: "dining",
        x: 420, y: 380, width: 90, height: 45,
        rooms: ["Food Court", "Costa Coffee", "Juice Bar"],
        facilities: ["Main Cafeteria", "Coffee Shop", "Outdoor Shaded Seating"],
        entranceNode: "n_a4",
        accessible: true
      },
      {
        id: "uos-a5",
        code: "A5",
        name: "Men's Student Center",
        nameAr: "مركز الطالب",
        zone: "Zone A",
        category: "student_life",
        x: 310, y: 380, width: 95, height: 45,
        rooms: ["Clubs Room", "Billiards", "Career Advisory"],
        facilities: ["Student Union", "Recreation Room", "ATM Machine", "Information Desk"],
        entranceNode: "n_a5",
        accessible: true
      },
      {
        id: "uos-a6",
        code: "A6",
        name: "Men's Student Forum",
        nameAr: "منتدى الطالب",
        zone: "Zone A",
        category: "student_life",
        x: 525, y: 400, width: 50, height: 40,
        rooms: ["Forum Main Stage", "Debate Room"],
        facilities: ["Multi-purpose Forum", "Exhibition Area"],
        entranceNode: "n_a6",
        accessible: true
      },
      {
        id: "uos-a7",
        code: "A7",
        name: "Central Library Building",
        nameAr: "مبنى المكتبة المركزية",
        zone: "Zone A",
        category: "library",
        x: 440, y: 440, width: 100, height: 70,
        rooms: ["LIB-Ground", "LIB-101 Silent Pod", "LIB-205 Group Study", "Audio-Visual Room"],
        facilities: ["Digital Media Pods", "Quiet Reading Halls", "Research Help Desk", "Prayer Room", "Elevators (All Floors)"],
        entranceNode: "n_a7",
        accessible: true
      },
      {
        id: "uos-a17",
        code: "A17",
        name: "Innovation Hub",
        nameAr: "مركز الابتكار",
        zone: "Zone A",
        category: "computing",
        x: 230, y: 400, width: 65, height: 40,
        rooms: ["Maker Space", "Incubator Lab", "VR Studio"],
        facilities: ["3D Printers", "Hackathon Arena", "Venture Mentorship"],
        entranceNode: "n_a17",
        accessible: true
      },
      {
        id: "uos-a16",
        code: "A16",
        name: "Men's Sports Complex",
        nameAr: "المجمع الرياضي - طالب",
        zone: "Zone A",
        category: "sports",
        x: 210, y: 455, width: 90, height: 65,
        rooms: ["Olympic Pool", "Fitness Gym", "Basketball Arena"],
        facilities: ["Gymnasium", "Indoor Swimming Pool", "Physiotherapy"],
        entranceNode: "n_a16",
        accessible: true
      },
      {
        id: "uos-a9",
        code: "A9",
        name: "College of Business & Computing (CCI)",
        nameAr: "كلية الحوسبة والمعلوماتية وإدارة الأعمال",
        zone: "Zone A",
        category: "computing",
        departments: ["College of Computing & Informatics", "College of Business Administration"],
        x: 430, y: 530, width: 70, height: 50,
        rooms: ["CCI-101", "CCI-104 AI Lab", "CCI-204 Cyber Lab", "B-210 Finance Lab"],
        facilities: ["High-Performance Computing Lab", "Bloomberg Terminal Lab", "Elevator North"],
        entranceNode: "n_a9",
        accessible: true
      },
      {
        id: "uos-a10",
        code: "A10",
        name: "Classrooms Building A10",
        nameAr: "قاعات دراسية A10",
        zone: "Zone A",
        category: "classroom",
        x: 350, y: 530, width: 65, height: 50,
        rooms: ["A10-101", "A10-102", "A10-201", "A10-204"],
        facilities: ["Smart Lecture Theatres", "Restrooms", "Water Dispensers"],
        entranceNode: "n_a10",
        accessible: true
      },
      {
        id: "uos-a8",
        code: "A8",
        name: "Classrooms Building A8",
        nameAr: "قاعات دراسية A8",
        zone: "Zone A",
        category: "classroom",
        x: 515, y: 530, width: 65, height: 50,
        rooms: ["A8-101", "A8-103", "A8-202"],
        facilities: ["Lecture Classrooms", "Study Pods"],
        entranceNode: "n_a8",
        accessible: true
      },
      {
        id: "uos-a11",
        code: "A11",
        name: "College of Sciences",
        nameAr: "كلية العلوم",
        zone: "Zone A",
        category: "science",
        departments: ["Applied Physics", "Chemistry", "Mathematics", "Biotechnology"],
        x: 320, y: 600, width: 70, height: 50,
        rooms: ["SCI-101", "Chem Lab 3", "Optics Lab", "Bio Lab 1"],
        facilities: ["Spectroscopy Lab", "Chemical Storage", "Emergency Showers"],
        entranceNode: "n_a11",
        accessible: true
      },
      {
        id: "uos-a13",
        code: "A13 (M8)",
        name: "College of Engineering (M8/M9)",
        nameAr: "كلية الهندسة - M8/M9",
        zone: "Zone A",
        category: "engineering",
        departments: ["Electrical & Computer Engineering", "Mechanical", "Civil", "Industrial"],
        x: 440, y: 600, width: 85, height: 60,
        rooms: ["M8-101", "M8-102", "M8-103", "M8-204 Circuits Lab", "M8-214 Faculty Office", "M9-Lab101"],
        facilities: ["Robotics & Mechatronics Lab", "Embedded Systems Lab", "Dean of Engineering", "Prayer Room (2nd floor)", "Elevator Central"],
        entranceNode: "n_a13",
        accessible: true
      },
      {
        id: "uos-a12",
        code: "A12",
        name: "Classrooms Building A12",
        nameAr: "قاعات دراسية A12",
        zone: "Zone A",
        category: "classroom",
        x: 370, y: 600, width: 55, height: 50,
        rooms: ["A12-101", "A12-102", "A12-205"],
        facilities: ["Engineering Drawing Lab", "Large Tiered Amphitheater"],
        entranceNode: "n_a12",
        accessible: true
      },
      {
        id: "uos-a14",
        code: "A14",
        name: "Classrooms Building A14",
        nameAr: "قاعات دراسية A14",
        zone: "Zone A",
        category: "classroom",
        x: 540, y: 600, width: 55, height: 50,
        rooms: ["A14-101", "A14-102", "A14-203"],
        facilities: ["Smart Boards", "Group Collaboration Pods"],
        entranceNode: "n_a14",
        accessible: true
      },

      // === ZONE B: CENTRAL ADMINISTRATION & LABS ===
      {
        id: "uos-b1",
        code: "B1",
        name: "Main Administration Building",
        nameAr: "المبنى الرئيسي",
        zone: "Zone B",
        category: "admin",
        departments: ["Chancellor's Office", "Board of Trustees", "Financial Affairs"],
        x: 490, y: 685, width: 105, height: 55,
        rooms: ["Chancellor Suite", "Finance Counter", "HR Office"],
        facilities: ["Executive Conference Hall", "ATM", "Information Helpdesk"],
        entranceNode: "n_b1",
        accessible: true
      },
      {
        id: "uos-b2",
        code: "B2",
        name: "Office of the Registrar",
        nameAr: "مكتب مسجل الجامعة",
        zone: "Zone B",
        category: "admin",
        departments: ["Admissions", "Registration & Records", "Student Accounts"],
        x: 450, y: 685, width: 35, height: 40,
        rooms: ["Reg Counter 1-8", "Student Card Issuance", "Transcripts Office"],
        facilities: ["Ticketing Queue System", "Waiting Lounge", "Ramp Access"],
        entranceNode: "n_b2",
        accessible: true
      },
      {
        id: "uos-b3",
        code: "B3-B4",
        name: "Central Laboratories Complex",
        nameAr: "المختبرات المركزية B3-B4",
        zone: "Zone B",
        category: "science",
        departments: ["Central Research Labs", "Materials Testing", "Microscopy"],
        x: 370, y: 675, width: 60, height: 75,
        rooms: ["Electron Microscopy Unit", "Clean Room", "Spectrometry Lab"],
        facilities: ["Advanced Analytical Instrumentation", "Bio-Safety Level 2"],
        entranceNode: "n_b3",
        accessible: true
      },

      // === ZONE C: WOMEN'S CAMPUS ===
      {
        id: "uos-c13",
        code: "C13 (W9)",
        name: "College of Engineering - Women (W9)",
        nameAr: "كلية الهندسة - طالبات (W9)",
        zone: "Zone C",
        category: "engineering",
        departments: ["Computer Engineering", "Architectural Engineering", "Sustainable Energy"],
        x: 440, y: 775, width: 85, height: 60,
        rooms: ["W9-010", "W9-015 CAD Studio", "W9-102 Electronics", "W9-204 Dean Annex"],
        facilities: ["Design Studios", "Computer Labs", "Elevator South", "Step-Free Ramp"],
        entranceNode: "n_c13",
        accessible: true
      },
      {
        id: "uos-c9",
        code: "C9",
        name: "Computing & IT - Women",
        nameAr: "كلية الحوسبة والمعلوماتية - طالبات",
        zone: "Zone C",
        category: "computing",
        x: 430, y: 855, width: 70, height: 50,
        rooms: ["C9-101", "C9-105 AI Studio", "C9-201 Data Science"],
        facilities: ["Software Engineering Labs", "Robotics Bench"],
        entranceNode: "n_c9",
        accessible: true
      },
      {
        id: "uos-c7",
        code: "C7",
        name: "Women's Library Building",
        nameAr: "مبنى المكتبة - طالبات",
        zone: "Zone C",
        category: "library",
        x: 440, y: 925, width: 100, height: 65,
        rooms: ["LIB-W-Ground", "LIB-W-Silent Pods", "Rare Books Archive"],
        facilities: ["Reading Rooms", "Computer Workstations", "Prayer Room", "Elevator"],
        entranceNode: "n_c7",
        accessible: true
      },
      {
        id: "uos-c5",
        code: "C5",
        name: "Women's Student Center",
        nameAr: "مركز الطالبات",
        zone: "Zone C",
        category: "student_life",
        x: 310, y: 1010, width: 95, height: 45,
        rooms: ["Student Council", "Activities Room", "Art Lounge"],
        facilities: ["Student Lounge", "Bookstore", "Copy Center"],
        entranceNode: "n_c5",
        accessible: true
      },
      {
        id: "uos-c4",
        code: "C4",
        name: "Women's Dining Hall",
        nameAr: "مجمع المطاعم - طالبات",
        zone: "Zone C",
        category: "dining",
        x: 420, y: 1010, width: 90, height: 45,
        rooms: ["Cafeteria Hall", "Subway", "Caribou Coffee"],
        facilities: ["Food Court", "Bakery", "Outdoor Courtyard"],
        entranceNode: "n_c4",
        accessible: true
      },
      {
        id: "uos-c15",
        code: "C15",
        name: "Women's Sports Complex",
        nameAr: "المجمع الرياضي - طالبات",
        zone: "Zone C",
        category: "sports",
        x: 300, y: 1110, width: 90, height: 60,
        rooms: ["Gym", "Aerobics Studio", "Indoor Courts"],
        facilities: ["Swimming Pool", "Cardio Zone", "Lockers"],
        entranceNode: "n_c15",
        accessible: true
      },

      // === ZONE E: MEDICAL & HEALTH SCIENCES ===
      {
        id: "uos-e5",
        code: "E5",
        name: "College of Medicine",
        nameAr: "كلية الطب",
        zone: "Zone E",
        category: "medical",
        departments: ["Basic Medical Sciences", "Clinical Sciences", "Anatomy"],
        x: 430, y: 1250, width: 110, height: 65,
        rooms: ["MED-Auditorium A", "Anatomy Dissection Lab", "MED-201"],
        facilities: ["Virtual Anatomy Table", "Simulation Center", "Elevators East & West"],
        entranceNode: "n_e5",
        accessible: true
      },
      {
        id: "uos-e1",
        code: "E1",
        name: "Jabir Bin Hayyan Building",
        nameAr: "مبنى جابر بن حيان (الصيدلة والعلوم الصحية)",
        zone: "Zone E",
        category: "medical",
        departments: ["College of Pharmacy", "College of Health Sciences"],
        x: 380, y: 1330, width: 110, height: 60,
        rooms: ["PHARM-101", "Sterile Compounding Lab", "Nursing Simulation"],
        facilities: ["Pharmaceutical Labs", "Audiology Suite", "Physical Therapy Clinic"],
        entranceNode: "n_e1",
        accessible: true
      },
      {
        id: "uos-e4",
        code: "E4",
        name: "Medical Library Building",
        nameAr: "مبنى المكتبة الطبية",
        zone: "Zone E",
        category: "library",
        x: 520, y: 1330, width: 80, height: 50,
        rooms: ["MedLib-Silent", "PubMed Search Center"],
        facilities: ["Biomedical Database Terminals", "Private Study Carrels"],
        entranceNode: "n_e4",
        accessible: true
      },
      {
        id: "uos-e9",
        code: "E9",
        name: "College of Dental Medicine",
        nameAr: "كلية طب الأسنان",
        zone: "Zone E",
        category: "medical",
        x: 330, y: 1405, width: 100, height: 55,
        rooms: ["DENT-Simulation Clinic", "Phantom Head Lab", "DENT-104"],
        facilities: ["Dental Phantom Simulation Units", "Sterilization Hub"],
        entranceNode: "n_e9",
        accessible: true
      },
      {
        id: "uos-e11",
        code: "E11",
        name: "University Dental Hospital Sharjah (UDHS)",
        nameAr: "مستشفى الأسنان الجامعي بالشارقة",
        zone: "Zone E",
        category: "medical",
        x: 230, y: 1405, width: 85, height: 70,
        rooms: ["Dental Triage", "Pediatric Clinic", "Oral Surgery Suites"],
        facilities: ["Outpatient Specialized Dental Clinics", "Emergency Dental Desk"],
        entranceNode: "n_e11",
        accessible: true
      }
    ],
    pois: [
      { id: "p_a1", name: "Parking A-P1 (Men's Engineering & Sci)", code: "A-P1", type: "parking", x: 620, y: 550, nodeId: "n_ap1", accessible: true },
      { id: "p_a2", name: "Parking A-P2 (Law & Humanities)", code: "A-P2", type: "parking", x: 530, y: 240, nodeId: "n_ap2", accessible: true },
      { id: "p_a3", name: "Parking A-P3 (North Dorms & Stadium)", code: "A-P3", type: "parking", x: 340, y: 160, nodeId: "n_ap3", accessible: true },
      { id: "p_b1", name: "Parking B-P1 (Admin & Registrar)", code: "B-P1", type: "parking", x: 620, y: 690, nodeId: "n_bp1", accessible: true },
      { id: "p_c1", name: "Parking C-P1 (Women's Engineering)", code: "C-P1", type: "parking", x: 620, y: 810, nodeId: "n_cp1", accessible: true },
      { id: "p_e1", name: "Parking E-P1 (Medical Colleges)", code: "E-P1", type: "parking", x: 600, y: 1280, nodeId: "n_ep1", accessible: true },
      { id: "g_a1", name: "Gate A1 (Men's Campus Main Gate)", code: "Gate A1", type: "gate", x: 670, y: 400, nodeId: "n_gate_a1", accessible: true },
      { id: "g_b", name: "Gate B (Administration Gate)", code: "Gate B", type: "gate", x: 670, y: 700, nodeId: "n_gate_b", accessible: true },
      { id: "g_c1", name: "Gate C1 (Women's Campus Gate)", code: "Gate C1", type: "gate", x: 670, y: 950, nodeId: "n_gate_c1", accessible: true },
      { id: "g_e1", name: "Gate E1 (Medical Campus Gate)", code: "Gate E1", type: "gate", x: 670, y: 1330, nodeId: "n_gate_e1", accessible: true },
      { id: "mosque_a", name: "Men's Campus Mosque / Musalla A13", code: "Musalla A13", type: "prayer", x: 485, y: 630, nodeId: "n_a13", accessible: true },
      { id: "mosque_lib", name: "Library Prayer Hall (2nd Floor)", code: "Musalla A7", type: "prayer", x: 490, y: 460, nodeId: "n_a7", accessible: true },
      { id: "mosque_c", name: "Women's Musalla C13", code: "Musalla C13", type: "prayer", x: 485, y: 805, nodeId: "n_c13", accessible: true }
    ],
    graph: {
      nodes: {
        "n_gate_a1": { x: 670, y: 400, label: "Gate A1 Entrance" },
        "n_ap1": { x: 620, y: 550, label: "Parking A-P1" },
        "n_ap2": { x: 530, y: 240, label: "Parking A-P2" },
        "n_ap3": { x: 340, y: 160, label: "Parking A-P3" },
        "n_a19": { x: 250, y: 155, label: "Stadium Gate" },
        "n_a1": { x: 485, y: 205, label: "Ibn Rushd Entrance" },
        "n_a2": { x: 435, y: 290, label: "Ibn Khaldun Entrance" },
        "n_a3": { x: 470, y: 365, label: "Ibn Al-Haytham Entrance" },
        "n_a4": { x: 465, y: 430, label: "Men's Dining Entry" },
        "n_a5": { x: 355, y: 430, label: "Student Center Entry" },
        "n_a6": { x: 550, y: 445, label: "Forum Entry" },
        "n_a7": { x: 490, y: 515, label: "Library South Portal" },
        "n_a17": { x: 260, y: 445, label: "Innovation Hub Entrance" },
        "n_a16": { x: 255, y: 525, label: "Sports Complex Gate" },
        "n_a9": { x: 465, y: 585, label: "CCI / Business Portal" },
        "n_a10": { x: 380, y: 585, label: "A10 Classrooms Entrance" },
        "n_a8": { x: 545, y: 585, label: "A8 Classrooms Entrance" },
        "n_a11": { x: 355, y: 655, label: "College of Sciences Entry" },
        "n_a13": { x: 480, y: 665, label: "Engineering M8 Main Portal" },
        "n_a12": { x: 395, y: 655, label: "A12 Classrooms Entrance" },
        "n_a14": { x: 565, y: 655, label: "A14 Classrooms Entrance" },
        "n_gate_b": { x: 670, y: 700, label: "Gate B Entrance" },
        "n_bp1": { x: 620, y: 690, label: "Parking B-P1" },
        "n_b1": { x: 540, y: 745, label: "Main Admin Portal" },
        "n_b2": { x: 465, y: 730, label: "Registrar Admission Counter" },
        "n_b3": { x: 400, y: 755, label: "Central Labs Entry" },
        "n_gate_c1": { x: 670, y: 950, label: "Gate C1 Entrance" },
        "n_cp1": { x: 620, y: 810, label: "Parking C-P1" },
        "n_c13": { x: 480, y: 840, label: "Engineering W9 Portal" },
        "n_c9": { x: 465, y: 910, label: "Women's CCI Portal" },
        "n_c7": { x: 490, y: 995, label: "Women's Library Portal" },
        "n_c5": { x: 355, y: 1060, label: "Women's Student Center" },
        "n_c4": { x: 465, y: 1060, label: "Women's Dining Entry" },
        "n_c15": { x: 345, y: 1175, label: "Women's Sports Complex" },
        "n_gate_e1": { x: 670, y: 1330, label: "Gate E1 Entrance" },
        "n_ep1": { x: 600, y: 1280, label: "Parking E-P1" },
        "n_e5": { x: 485, y: 1320, label: "Medicine College Portal" },
        "n_e1": { x: 435, y: 1395, label: "Pharmacy & Health Sci Entry" },
        "n_e4": { x: 560, y: 1385, label: "Medical Library Portal" },
        "n_e9": { x: 380, y: 1465, label: "Dental College Portal" },
        "n_e11": { x: 270, y: 1480, label: "Dental Hospital Entrance" }
      },
      edges: [
        ["n_ap3", "n_a1", 150, true, false, "Walkway past Ibn Rushd Gardens"],
        ["n_ap3", "n_a19", 110, true, false, "Paved walkway to Stadium"],
        ["n_ap2", "n_a1", 120, true, false, "Shaded walkway from Parking A-P2"],
        ["n_ap2", "n_a2", 90, true, true, "Covered corridor to Ibn Khaldun"],
        ["n_a1", "n_a2", 95, true, true, "Central pedestrian arcade"],
        ["n_a2", "n_a3", 85, true, true, "Central pedestrian arcade"],
        ["n_a3", "n_a4", 80, true, true, "Covered promenade toward Dining"],
        ["n_a4", "n_a5", 110, true, true, "Student Plaza Walkway"],
        ["n_a4", "n_a6", 90, true, true, "Forum Shaded Corridor"],
        ["n_a5", "n_a17", 95, true, true, "Path to Innovation Hub"],
        ["n_a17", "n_a16", 85, true, true, "Paved path to Sports Complex"],
        ["n_a4", "n_a7", 75, true, true, "Main Library Plaza Entrance"],
        ["n_a7", "n_a9", 80, true, true, "Covered Arcade to Computing"],
        ["n_a9", "n_a10", 85, true, true, "Classrooms Concourse"],
        ["n_a9", "n_a8", 85, true, true, "East Classrooms Concourse"],
        ["n_a9", "n_a13", 80, true, true, "Direct Shaded Walkway into Engineering M8"],
        ["n_a10", "n_a12", 70, true, true, "West Quad Corridor"],
        ["n_a10", "n_a11", 90, true, true, "Walkway to Sciences"],
        ["n_a8", "n_a14", 70, true, true, "East Quad Corridor"],
        ["n_a12", "n_a13", 85, true, true, "Engineering Lab Link"],
        ["n_a14", "n_a13", 85, true, true, "Engineering Courtyard link"],
        ["n_gate_a1", "n_ap1", 160, true, false, "Main Vehicle & Pedestrian Boulevard"],
        ["n_ap1", "n_a8", 80, true, true, "Gate A1 Direct Walkway to East Concourse"],
        ["n_ap1", "n_a14", 85, true, true, "East Parking Entrance to Classrooms"],
        ["n_ap1", "n_a13", 140, true, true, "Shaded pathway into M8 Engineering South Portal"],
        ["n_a13", "n_b2", 75, true, true, "Central Plaza Pedestrian Overpass / Ground Walkway"],
        ["n_b2", "n_b1", 80, true, true, "Covered Administration Arcade"],
        ["n_b2", "n_b3", 75, true, true, "Pathway to Central Laboratories"],
        ["n_gate_b", "n_bp1", 60, true, false, "Admin Gate Driveway"],
        ["n_bp1", "n_b1", 85, true, true, "Admin Parking Walkway to Chancellor Portal"],
        ["n_b1", "n_c13", 110, true, true, "Central Boulevard to Women's Engineering W9"],
        ["n_b2", "n_c13", 120, true, true, "Direct covered path to W9 Portal"],
        ["n_c13", "n_c9", 80, true, true, "Women's Concourse to Computing"],
        ["n_c9", "n_c7", 85, true, true, "Arcade to Women's Library"],
        ["n_c7", "n_c4", 75, true, true, "Library Walkway to Dining Hall"],
        ["n_c4", "n_c5", 110, true, true, "Women's Student Center Plaza"],
        ["n_c5", "n_c15", 120, true, true, "Pathway to Sports Complex"],
        ["n_gate_c1", "n_cp1", 150, true, false, "Women's Gate Entry Drive"],
        ["n_cp1", "n_c13", 140, true, true, "Parking C-P1 Shaded Walkway to W9"],
        ["n_c4", "n_e5", 260, true, false, "Pedestrian Campus Connector to Medical City"],
        ["n_gate_e1", "n_ep1", 90, true, false, "Gate E1 Entrance Road"],
        ["n_ep1", "n_e5", 95, true, true, "Walkway to College of Medicine"],
        ["n_e5", "n_e1", 100, true, true, "Covered Walkway to Pharmacy & Health Sciences"],
        ["n_e5", "n_e4", 90, true, true, "Path to Medical Library"],
        ["n_e1", "n_e9", 90, true, true, "Shaded pathway to Dental Medicine"],
        ["n_e9", "n_e11", 110, true, true, "Direct corridor to Dental Hospital"]
      ]
    }
  },

  aus: {
    id: "aus",
    name: "American University of Sharjah",
    shortName: "AUS",
    fullName: "American University of Sharjah — Campus Masterplan",
    city: "Sharjah University City, UAE",
    viewBox: "0 0 1200 900",
    defaultCenter: { x: 600, y: 450 },
    defaultZoom: 1,
    description: "Iconic classical quadrangle campus centered around the Grand Main Building Auditorium, flanked by the Engineering Wing, CAAD, and the Student Center.",
    sectors: [
      { id: "all", name: "Full Campus", bounds: { minX: 0, minY: 0, maxX: 1200, maxY: 900 } },
      { id: "plaza", name: "Central Grand Plaza", bounds: { minX: 350, minY: 150, maxX: 850, maxY: 650 } },
      { id: "eng", name: "Engineering Wing", bounds: { minX: 50, minY: 150, maxX: 450, maxY: 600 } },
      { id: "caad", name: "Architecture & Arts (CAAD)", bounds: { minX: 650, minY: 350, maxX: 1150, maxY: 800 } }
    ],
    quickJumps: [
      { label: "Engineering Building 1 (EB1)", targetId: "aus-2", room: "EB1-102", icon: "engineering" },
      { label: "Main Building Auditorium (1)", targetId: "aus-1", room: "Main Rotunda", icon: "admin" },
      { label: "Architecture CAAD (4)", targetId: "aus-4", room: "Design Studio 201", icon: "art" },
      { label: "School of Business (SBA)", targetId: "aus-6", room: "SBA-001", icon: "business" },
      { label: "Student Center & Food Court", targetId: "aus-sc", room: "Food Court", icon: "dining" },
      { label: "Main Library", targetId: "aus-lib", room: "Quiet Study Pods", icon: "library" },
      { label: "Campus Mosque", targetId: "aus-mosque", room: "Prayer Hall", icon: "prayer" }
    ],
    buildings: [
      {
        id: "aus-1",
        code: "1",
        name: "Main Building & Auditorium",
        nameAr: "المبنى الرئيسي وقاعة الاحتفالات",
        zone: "Central Plaza",
        category: "admin",
        departments: ["Chancellor", "Registrar & Admissions", "Main Auditorium", "Cashier"],
        x: 520, y: 200, width: 160, height: 95,
        rooms: ["Auditorium Main Hall", "Admissions Hall", "Rotunda Gallery", "Cashier Counter"],
        facilities: ["Grand Colonnade", "Visitor Welcome Desk", "Elevators to Executive Floor", "Wheelchair Ramps"],
        entranceNode: "n_aus_1",
        accessible: true
      },
      {
        id: "aus-2",
        code: "2",
        name: "College of Engineering 1 (EB1) & Humanities",
        nameAr: "كلية الهندسة 1 والعلوم الإنسانية",
        zone: "Engineering Quad",
        category: "engineering",
        departments: ["Electrical Engineering", "Civil Engineering", "Humanities & Sciences"],
        x: 270, y: 230, width: 140, height: 75,
        rooms: ["EB1-101", "EB1-102", "EB1-205 Electronics Lab", "Physics Lecture Hall"],
        facilities: ["Circuits & Microcontroller Labs", "Faculty Offices", "Prayer Room", "Elevator North"],
        entranceNode: "n_aus_2",
        accessible: true
      },
      {
        id: "aus-3",
        code: "3",
        name: "College of Engineering 2 (EB2)",
        nameAr: "كلية الهندسة 2",
        zone: "Engineering Quad",
        category: "engineering",
        departments: ["Computer Science & Engineering", "Mechanical Engineering", "Chemical Engineering"],
        x: 200, y: 210, width: 110, height: 60,
        rooms: ["EB2-015 Networking Lab", "EB2-110", "EB2-202 AI Lab"],
        facilities: ["GPU Computing Cluster", "Robotics Bay", "Student Project Lounge"],
        entranceNode: "n_aus_3",
        accessible: true
      },
      {
        id: "aus-12",
        code: "12",
        name: "Engineering Sciences Building",
        nameAr: "مبنى العلوم الهندسية والمختبرات",
        zone: "Engineering Quad",
        category: "engineering",
        departments: ["Heavy Materials Lab", "Fluids & Aerodynamics", "Workshop"],
        x: 60, y: 240, width: 140, height: 110,
        rooms: ["Heavy Structures Lab", "Wind Tunnel", "Machining Center"],
        facilities: ["CNC Machines", "Overhead Crane", "Industrial Testing Equipment"],
        entranceNode: "n_aus_12",
        accessible: true
      },
      {
        id: "aus-lib",
        code: "LIB",
        name: "AUS Main Library",
        nameAr: "مكتبة الجامعة الأمريكية",
        zone: "Central Plaza",
        category: "library",
        x: 420, y: 160, width: 85, height: 65,
        rooms: ["Ground Floor Commons", "2nd Floor Silent Carrels", "Group Study 1-6"],
        facilities: ["High-speed Scanning", "Research Consultation", "Silent Reading Pods", "Elevator"],
        entranceNode: "n_aus_lib",
        accessible: true
      },
      {
        id: "aus-sc",
        code: "SC",
        name: "Student Center & Food Court",
        nameAr: "مركز الطلاب ومجمع المطاعم",
        zone: "Central Plaza",
        category: "student_life",
        departments: ["Student Affairs", "Health Center", "Pharmacy", "Food Court"],
        x: 480, y: 340, width: 140, height: 80,
        rooms: ["Food Court Main", "Health Clinic", "Student Council", "Pharmacy"],
        facilities: ["Starbucks", "Subway", "Campus Clinic", "Recreation & Billiards", "ATM / Bank"],
        entranceNode: "n_aus_sc",
        accessible: true
      },
      {
        id: "aus-4",
        code: "4",
        name: "Architecture, Art and Design 1 (CAAD 1)",
        nameAr: "كلية العمارة والفنون والتصميم 1",
        zone: "CAAD Sector",
        category: "art",
        departments: ["Architecture", "Interior Design"],
        x: 580, y: 360, width: 95, height: 65,
        rooms: ["Studio 101", "Design Critique Space", "Print Lab"],
        facilities: ["Laser Cutters", "Wood Workshop", "Drafting Tables"],
        entranceNode: "n_aus_4",
        accessible: true
      },
      {
        id: "aus-5",
        code: "5",
        name: "Architecture, Art and Design 2 (CAAD 2)",
        nameAr: "كلية العمارة والفنون والتصميم 2",
        zone: "CAAD Sector",
        category: "art",
        departments: ["Visual Communication", "Design Management"],
        x: 520, y: 415, width: 95, height: 65,
        rooms: ["Darkroom", "Digital Media Lab", "Exhibition Gallery"],
        facilities: ["Photography Studio", "Mac Pro Labs"],
        entranceNode: "n_aus_5",
        accessible: true
      },
      {
        id: "aus-6",
        code: "6",
        name: "School of Business Administration (SBA)",
        nameAr: "كلية إدارة الأعمال",
        zone: "East Wing",
        category: "business",
        departments: ["Finance", "Management", "Marketing", "Economics"],
        x: 630, y: 160, width: 95, height: 55,
        rooms: ["SBA-001 Tiered Auditorium", "Trading Room", "SBA-105"],
        facilities: ["Interactive Trading Simulation Lab", "Executive Classrooms"],
        entranceNode: "n_aus_6",
        accessible: true
      },
      {
        id: "aus-7",
        code: "7",
        name: "Physics Building",
        nameAr: "مبنى الفيزياء",
        zone: "East Wing",
        category: "science",
        x: 820, y: 290, width: 75, height: 50,
        rooms: ["PHYS-101", "General Physics Lab", "Optics Room"],
        facilities: ["Modern Physics Experimental Setup"],
        entranceNode: "n_aus_7",
        accessible: true
      },
      {
        id: "aus-8",
        code: "8",
        name: "Chemistry Building",
        nameAr: "مبنى الكيمياء",
        zone: "East Wing",
        category: "science",
        x: 740, y: 260, width: 75, height: 50,
        rooms: ["CHEM-101", "Organic Chemistry Lab", "Analytical Lab"],
        facilities: ["Fume Hoods", "Instrumentation Laboratory"],
        entranceNode: "n_aus_8",
        accessible: true
      },
      {
        id: "aus-mosque",
        code: "MOSQUE",
        name: "Campus Mosque",
        nameAr: "مسجد الحرم الجامعي",
        zone: "Engineering Quad",
        category: "prayer",
        x: 395, y: 270, width: 45, height: 45,
        rooms: ["Main Prayer Hall", "Ablution Facilities"],
        facilities: ["Minaret & Dome", "Daily Congregation Prayers", "Friday Prayer Space"],
        entranceNode: "n_aus_mosque",
        accessible: true
      }
    ],
    pois: [
      { id: "aus_p16", name: "Visitor Parking P16", code: "P16", type: "parking", x: 345, y: 325, nodeId: "n_aus_p16", accessible: true },
      { id: "aus_p3", name: "Student Parking P3 (South)", code: "P3", type: "parking", x: 440, y: 560, nodeId: "n_aus_p3", accessible: true },
      { id: "aus_p5", name: "Free Parking P5/P6 (East)", code: "P5", type: "parking", x: 710, y: 570, nodeId: "n_aus_p5", accessible: true },
      { id: "aus_gate_main", name: "AUS Main Gate", code: "Main Gate", type: "gate", x: 960, y: 440, nodeId: "n_aus_gate_main", accessible: true },
      { id: "aus_gate_airport", name: "Airport Gate", code: "Airport Gate", type: "gate", x: 120, y: 70, nodeId: "n_aus_gate_airport", accessible: true },
      { id: "aus_bus", name: "Campus Bus & Taxi Stand", code: "Transit Stop", type: "bus", x: 910, y: 345, nodeId: "n_aus_bus", accessible: true }
    ],
    graph: {
      nodes: {
        "n_aus_gate_main": { x: 960, y: 440, label: "Main Campus Gate" },
        "n_aus_gate_airport": { x: 120, y: 70, label: "Airport Gate" },
        "n_aus_bus": { x: 910, y: 345, label: "Bus & Taxi Stand" },
        "n_aus_1": { x: 600, y: 300, label: "Main Building Grand Portal" },
        "n_aus_lib": { x: 460, y: 230, label: "Library Entrance" },
        "n_aus_2": { x: 340, y: 310, label: "Engineering EB1 Entrance" },
        "n_aus_3": { x: 260, y: 275, label: "Engineering EB2 Entrance" },
        "n_aus_12": { x: 140, y: 355, label: "Engineering Sciences Building" },
        "n_aus_mosque": { x: 415, y: 320, label: "Mosque Courtyard" },
        "n_aus_sc": { x: 550, y: 425, label: "Student Center Main Entrance" },
        "n_aus_4": { x: 630, y: 430, label: "CAAD 1 Main Portal" },
        "n_aus_5": { x: 570, y: 485, label: "CAAD 2 Main Portal" },
        "n_aus_6": { x: 680, y: 220, label: "SBA Business Entrance" },
        "n_aus_7": { x: 860, y: 345, label: "Physics Entrance" },
        "n_aus_8": { x: 780, y: 315, label: "Chemistry Entrance" },
        "n_aus_p16": { x: 345, y: 325, label: "Visitor Parking P16" },
        "n_aus_p3": { x: 440, y: 560, label: "Student Parking P3" },
        "n_aus_p5": { x: 710, y: 570, label: "Free Parking P5" }
      },
      edges: [
        ["n_aus_gate_main", "n_aus_bus", 110, true, false, "Boulevard Entry to Transit Hub"],
        ["n_aus_bus", "n_aus_7", 75, true, true, "Walkway into Sciences Courtyard"],
        ["n_aus_7", "n_aus_8", 70, true, true, "Inter-Science Covered Walkway"],
        ["n_aus_8", "n_aus_1", 120, true, true, "Grand Plaza East Walkway"],
        ["n_aus_1", "n_aus_6", 75, true, true, "Colonnade Arcade to School of Business"],
        ["n_aus_1", "n_aus_lib", 90, true, true, "Rotunda Plaza to Library"],
        ["n_aus_lib", "n_aus_mosque", 65, true, true, "Shaded pathway past Mosque"],
        ["n_aus_mosque", "n_aus_2", 70, true, true, "Mosque Plaza into Engineering EB1"],
        ["n_aus_2", "n_aus_3", 75, true, true, "Engineering Corridor Link"],
        ["n_aus_3", "n_aus_12", 110, true, true, "Paved walkway to Heavy Labs"],
        ["n_aus_gate_airport", "n_aus_12", 140, true, false, "Airport Gate Avenue"],
        ["n_aus_p16", "n_aus_2", 40, true, true, "Direct parking ramp to EB1"],
        ["n_aus_1", "n_aus_sc", 100, true, true, "Grand Central Plaza Walkway"],
        ["n_aus_2", "n_aus_sc", 130, true, true, "Engineering Walkway to Student Center"],
        ["n_aus_sc", "n_aus_4", 75, true, true, "Student Plaza to CAAD 1"],
        ["n_aus_4", "n_aus_5", 65, true, true, "CAAD Courtyard Link"],
        ["n_aus_p3", "n_aus_sc", 120, true, true, "South Parking Walkway into Dining"],
        ["n_aus_p5", "n_aus_5", 130, true, true, "East Parking Walkway to CAAD"]
      ]
    }
  },

  rit: {
    id: "rit",
    name: "RIT Dubai",
    shortName: "RIT Dubai",
    fullName: "Rochester Institute of Technology Dubai — Silicon Oasis Campus",
    city: "Dubai Silicon Oasis, UAE",
    viewBox: "0 0 1000 800",
    defaultCenter: { x: 500, y: 400 },
    defaultZoom: 1,
    description: "State-of-the-art innovation campus in Dubai Silicon Oasis, featuring high-tech robotics arenas, tiered design studios, and smart solar-shaded pedestrian promenades.",
    sectors: [
      { id: "all", name: "Full Campus", bounds: { minX: 0, minY: 0, maxX: 1000, maxY: 800 } },
      { id: "academic", name: "Innovation & Academic Core", bounds: { minX: 180, minY: 160, maxX: 820, maxY: 620 } }
    ],
    quickJumps: [
      { label: "Block A — Administration & Admissions", targetId: "rit-block-a", room: "Admissions Counter", icon: "admin" },
      { label: "Innovation Dome & MakerSpace (Block I)", targetId: "rit-dome", room: "Robotics Arena", icon: "computing" },
      { label: "Block D — Electrical & Computing (AI)", targetId: "rit-block-d", room: "Room 114", icon: "engineering" },
      { label: "Block G — Library Commons", targetId: "rit-block-g", room: "Silent Floor", icon: "library" },
      { label: "Silicon Eatery & Canteen", targetId: "rit-canteen", room: "Food Hall", icon: "dining" },
      { label: "Block B — Sciences & Liberal Arts", targetId: "rit-block-b", room: "Physics Lab 2", icon: "academic" }
    ],
    buildings: [
      {
        id: "rit-dome",
        code: "DOME",
        name: "Innovation Dome (Block I)",
        nameAr: "قبة الابتكار والتصنيع",
        zone: "Central Innovation Core",
        category: "computing",
        shape: "dome",
        departments: ["Robotics & Mechatronics", "3D Prototyping & Incubation", "AI Discovery Center"],
        x: 455, y: 305, width: 90, height: 90,
        rooms: ["Robotics Bay", "Maker Space 102", "Drone Flight Cage", "AR/VR Immersion Lab"],
        facilities: ["Industrial 3D Printing Farm", "Rapid Electronics Soldering", "Central Rotunda Stage"],
        entranceNode: "n_rit_dome",
        accessible: true
      },
      {
        id: "rit-block-a",
        code: "BLK A",
        name: "Block A — Administration & Student Affairs",
        nameAr: "المبنى أ — الإدارة وشؤون الطلاب",
        zone: "South Entrance Wing",
        category: "admin",
        shape: "portal",
        departments: ["Admissions Office", "Registrar", "Financial Aid", "Career Advisory"],
        x: 420, y: 520, width: 160, height: 75,
        rooms: ["Admissions Lounge", "Financial Services Counter", "Registrar Hall", "Executive Suite"],
        facilities: ["Grand Colonnade Portico", "Wheelchair Accessibility Ramp", "Elevators to Executive Floor"],
        entranceNode: "n_rit_a",
        accessible: true
      },
      {
        id: "rit-block-b",
        code: "BLK B",
        name: "Block B — Science & Liberal Arts Department",
        nameAr: "المبنى ب — العلوم والآداب",
        zone: "West Academic Wing",
        category: "academic",
        shape: "l-shape",
        departments: ["Natural Sciences", "Mathematics & Statistics", "Psychology & Humanities"],
        x: 240, y: 460, width: 140, height: 85,
        rooms: ["Physics Lab 2", "Chemistry Hall 104", "Statistics Seminar Room"],
        facilities: ["Fume Hoods & Bio-Safety Equipment", "Faculty Suites", "Accessible Ramps"],
        entranceNode: "n_rit_b",
        accessible: true
      },
      {
        id: "rit-block-c",
        code: "BLK C",
        name: "Block C — Business & Management Department",
        nameAr: "المبنى ج — إدارة الأعمال",
        zone: "West Academic Wing",
        category: "admin",
        shape: "wing",
        departments: ["Finance & FinTech", "Supply Chain Management", "Marketing & Entrepreneurship"],
        x: 270, y: 320, width: 140, height: 80,
        rooms: ["Bloomberg Terminal Suite", "Executive Boardroom", "Room C-205"],
        facilities: ["Financial Trading Floor", "Interactive Collaboration Screens", "Elevators"],
        entranceNode: "n_rit_c",
        accessible: true
      },
      {
        id: "rit-block-d",
        code: "BLK D",
        name: "Block D — Electrical Eng & Computing Department",
        nameAr: "المبنى د — الهندسة الكهربائية والحوسبة",
        zone: "North Tech Wing",
        category: "engineering",
        shape: "wing",
        departments: ["Computer Science", "Cybersecurity", "Electrical & Microelectronics"],
        x: 340, y: 180, width: 150, height: 80,
        rooms: ["Cyber Defense Operations", "AI Supercomputer Room", "Room 114", "Embedded Systems Lab"],
        facilities: ["Dual-Screen Dev Stations", "GPU Cluster Connection", "Smart Classrooms"],
        entranceNode: "n_rit_d",
        accessible: true
      },
      {
        id: "rit-block-e",
        code: "BLK E",
        name: "Block E — Mechanical & Industrial Engineering",
        nameAr: "المبنى هـ — الهندسة الميكانيكية والصناعية",
        zone: "North Tech Wing",
        category: "engineering",
        shape: "wing",
        departments: ["Mechanical Engineering", "Industrial & Systems", "Thermal Sciences"],
        x: 560, y: 180, width: 150, height: 80,
        rooms: ["Aerodynamics & Wind Tunnel", "Thermodynamics Lab", "Materials Stress Analysis"],
        facilities: ["Heavy Testing Rig", "Industrial CNC Machinery", "Overhead Service Hoist"],
        entranceNode: "n_rit_e",
        accessible: true
      },
      {
        id: "rit-block-g",
        code: "BLK G",
        name: "Block G — Library & Information Commons",
        nameAr: "المبنى ز — المكتبة ومركز المعلومات",
        zone: "East Academic Wing",
        category: "library",
        shape: "atrium",
        departments: ["University Library", "Digital Research Commons", "Academic Tutoring"],
        x: 640, y: 320, width: 140, height: 85,
        rooms: ["Study Pod 1-8", "Silent Reading Gallery", "Rare Archives Room"],
        facilities: ["Acoustic Quiet Pods", "Ergonomic Desks", "Coffee Corner"],
        entranceNode: "n_rit_g",
        accessible: true
      },
      {
        id: "rit-block-h",
        code: "BLK H",
        name: "Block H — Arts & Design Department",
        nameAr: "المبنى ح — الفنون والتصميم",
        zone: "East Academic Wing",
        category: "academic",
        shape: "wing",
        departments: ["Graphic Design", "Interior Architecture", "Digital Media Production"],
        x: 630, y: 470, width: 135, height: 75,
        rooms: ["Studio H-101", "Mac Design Lab", "Darkroom & Print Workshop"],
        facilities: ["Large Format Plotters", "Color Calibration Workstations", "Drafting Tables"],
        entranceNode: "n_rit_h",
        accessible: true
      },
      {
        id: "rit-canteen",
        code: "CAFE",
        name: "Canteen & Silicon Student Eatery",
        nameAr: "المطعم والمركز الطلابي",
        zone: "Social Plaza",
        category: "dining",
        shape: "terrace",
        departments: ["Student Dining", "Al Dente Eatery", "Starbucks Lounge"],
        x: 790, y: 420, width: 120, height: 75,
        rooms: ["Food Hall", "Starbucks Lounge", "Outdoor Terrace"],
        facilities: ["Healthy Eateries", "Al Fresco Covered Dining", "Billiards & Gaming Lounge"],
        entranceNode: "n_rit_cafe",
        accessible: true
      },
      {
        id: "rit-sports",
        code: "SPORTS",
        name: "Sports Pavilion & Track Field",
        nameAr: "المجمع الرياضي ومضمار الجري",
        zone: "Athletics Sector",
        category: "sports",
        shape: "track",
        departments: ["Athletics Department", "Fitness & Recreation"],
        x: 80, y: 480, width: 150, height: 95,
        rooms: ["Athletic Field", "Locker Rooms", "Fitness Gym"],
        facilities: ["Synthetic Turf Pitch", "All-Weather Running Track", "Grandstand Seating"],
        entranceNode: "n_rit_sports",
        accessible: true
      }
    ],
    pois: [
      { id: "rit_p1", name: "Main Visitor & Student Parking P1", code: "P1", type: "parking", x: 490, y: 100, nodeId: "n_rit_p1", accessible: true },
      { id: "rit_p2", name: "East Student Parking P2", code: "P2", type: "parking", x: 860, y: 250, nodeId: "n_rit_p2", accessible: true },
      { id: "rit_gate", name: "Silicon Oasis Main Campus Gate", code: "Main Gate", type: "gate", x: 490, y: 40, nodeId: "n_rit_gate", accessible: true }
    ],
    graph: {
      nodes: {
        "n_rit_gate": { x: 490, y: 40, label: "Campus Entry Gate" },
        "n_rit_p1": { x: 490, y: 100, label: "Main Parking P1" },
        "n_rit_p2": { x: 860, y: 250, label: "East Parking P2" },
        "n_rit_d": { x: 415, y: 220, label: "Block D Entrance" },
        "n_rit_e": { x: 635, y: 220, label: "Block E Entrance" },
        "n_rit_dome": { x: 500, y: 350, label: "Innovation Dome Portal" },
        "n_rit_c": { x: 340, y: 360, label: "Block C Entrance" },
        "n_rit_b": { x: 310, y: 500, label: "Block B Entrance" },
        "n_rit_a": { x: 500, y: 520, label: "Block A Main Admin Entrance" },
        "n_rit_h": { x: 690, y: 510, label: "Block H Entrance" },
        "n_rit_g": { x: 710, y: 360, label: "Block G Library Portal" },
        "n_rit_cafe": { x: 820, y: 460, label: "Canteen Eatery Portal" },
        "n_rit_sports": { x: 155, y: 530, label: "Sports Pavilion Entrance" }
      },
      edges: [
        ["n_rit_gate", "n_rit_p1", 60, true, false, "Boulevard Access"],
        ["n_rit_p1", "n_rit_d", 110, true, true, "North Shaded Walkway to Block D"],
        ["n_rit_p1", "n_rit_e", 120, true, true, "North Shaded Walkway to Block E"],
        ["n_rit_d", "n_rit_e", 100, true, true, "Connecting Bridge Concourse"],
        ["n_rit_d", "n_rit_dome", 95, true, true, "Innovation Promenade West"],
        ["n_rit_e", "n_rit_dome", 95, true, true, "Innovation Promenade East"],
        ["n_rit_d", "n_rit_c", 80, true, true, "West Shaded Colonnade"],
        ["n_rit_c", "n_rit_b", 85, true, true, "Science Quad Link"],
        ["n_rit_b", "n_rit_a", 100, true, true, "South Administration Arcade"],
        ["n_rit_dome", "n_rit_a", 85, true, true, "Central Palm Plaza Promenade"],
        ["n_rit_a", "n_rit_h", 100, true, true, "Arts & Design Concourse"],
        ["n_rit_h", "n_rit_g", 85, true, true, "East Library Promenade"],
        ["n_rit_e", "n_rit_g", 80, true, true, "Commons Shaded Arcade"],
        ["n_rit_g", "n_rit_cafe", 75, true, true, "Student Plaza to Canteen"],
        ["n_rit_h", "n_rit_cafe", 80, true, true, "Terrace Walkway"],
        ["n_rit_p2", "n_rit_g", 90, true, true, "East Parking Walkway"],
        ["n_rit_b", "n_rit_sports", 95, true, true, "Paved Walkway to Athletics Track"]
      ]
    }
  }
};

// Export for ES modules and browser window
if (typeof window !== "undefined") {
  window.CAMPUS_DATA = CAMPUS_DATA;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = CAMPUS_DATA;
}
